In [1]:
# Create a program that calculates the area of a circle given its radius. 
import math as m
rad = float(input("Radius: "))

sol = (m.pi)*pow(rad,2)
print(sol)

12.566370614359172


In [2]:
# Find Armstrong number in range (0,1000)

def armstng(n):
    if n != 1001:
        sum =0
        temp = n
        while(temp>0):
            rem = temp%10
            sum=sum+pow(rem,3)
            temp = temp//10
        if sum == n:
            print(n,"It is Armstrong Number")
        return armstng(n+1)

        
armstng(0)    


0 It is Armstrong Number
1 It is Armstrong Number
153 It is Armstrong Number
370 It is Armstrong Number
371 It is Armstrong Number
407 It is Armstrong Number


In [3]:
# Check where the given number is prime or not? 

def chk_prime(n):
    if(n%5 != 0 and n!=5 and n%1==0):
        print("Prime Number")
    elif(n==5):
        print("Prime Number")
    else:
        print("Non-Prime")
chk_prime(72)

Prime Number


In [4]:
# Implement a program that counts the number of vowels in a given string. 
vow = ['a','e','i','o','u']
cnt = [0,0,0,0,0]
vow_cnt=dict(zip(vow,cnt))
str = input("Enter a string: ")
for ch in str:
    if ch in vow:
        vow_cnt[ch]+=1 
vow_cnt

{'a': 0, 'e': 0, 'i': 0, 'o': 0, 'u': 0}

In [5]:
# Create a program that checks if a given word, is a palindrome. 

str = input("Enter a word: ")
rev_str = str[::-1]
if(str == rev_str):
    print("Palindrome String")
else:
    print("Not ")

Not 


In [6]:
# Write a one-liner using list comprehension to generate a list of squares of numbers from 1 to 10. 

num_sq = [pow(sq,2) for sq in range(1,10) ]
num_sq

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [7]:
# Implement a function that takes a list of temperatures in Celsius and uses the map function to convert them to Fahrenheit. 
def cn_frht(x):
    fht = (1.8*x) +32
    return "%.2f" % fht

lst = list(map(cn_frht,[56,67,34,100,43,0]))
lst


['132.80', '152.60', '93.20', '212.00', '109.40', '32.00']

In [8]:
# Implement a program that checks if a given number is even or odd without modular operator. 
def chk_num(n):
    if n & 1 == 0:
        print("Even Number")
    else:
        print("Odd number")
num = int(input("Enter Number"))
chk_num(num)



Even Number


In [9]:
# Write a program that determines whether a year is a leap year or not. 

year = int(input("Enter year : "))
if year%4==0 | year%100==0:
    print("Leap Year")
else:
    print("Not Leap Year")

Not Leap Year


In [10]:
# Create a program to print a right-angled triangle pattern using asterisks. 
n = int(input("Enter a Number: "))
for i in range(n+1):
    for j in range(i):
        print("* ",end=" ")
    print("\n")



*  

*  *  

*  *  *  

*  *  *  *  



In [11]:
# Write a program to print the Fibonacci sequence up to a specified number of terms. 
n = int(input("Enter a Number: "))
a = 0;b=1
for i in range(n+1):
    print(a," ",end=" ")
    a,b=b+a,a

0   1   1   2   3   

In [9]:
for i in range(3,0,-1):
    print(i)

3
2
1


In [18]:
# Implement a program to generate the following pattern: 
'''

4 

4 3 

4 3 2 

4 3 2 1 

'''

num = int(input("Enter a number"))
for i in range(1,num+1):
#     print(i,"iteration")
    for j in range(num,num-i,-1):
        print(j," ",end=" ")
    print("\n")

Enter a number4
4   

4   3   

4   3   2   

4   3   2   1   



In [32]:
'''
   4 

  4 3 

 4 3 2 

4 3 2 1 
'''
num = int(input("Enter a number"))
for i in range(1,num+1):
#     print(i,"iteration")
    print(" "*(num-i),end=" ")
    for j in range(num,num-i,-1):
        print(j," ",end=" ")
    print("\n")

Enter a number4
    4   

   4   3   

  4   3   2   

 4   3   2   1   



In [14]:
# Write a program to read data from a file and display it on the console.
f = open("file.txt","r+")
line = "ghdgfjfytukdtuyhdjmytnjy \ndfhdfghkmjmdrfghkmdty \ndfjdghkcdyhsmk,ryjrytjuyt"
f.write(line)
f.close()


In [15]:
f = open("file.txt","r+")
# while f:
print(f.read())
#     if not line:
#         break
f.close()

ghdgfjfytukdtuyhdjmytnjy 
dfhdfghkmjmdrfghkmdty 
dfjdghkcdyhsmk,ryjrytjuytyt


In [1]:
import pickle

In [3]:
# Pickling
cars = ["maruti","suzuki","lenovo","duster"]
bike = ["maruti","suzuki","lenovo","duster"]
file= "mycar.pkl"
f = open(file,"wb")
pickle.dump([bike,cars],f)
f.close()


In [5]:
file = "mycar.pkl"
f = open(file,"rb")
mycar = pickle.load(f)
print(mycar)
f.close()
print(type(mycar))

[['maruti', 'suzuki', 'lenovo', 'duster'], ['maruti', 'suzuki', 'lenovo', 'duster']]
<class 'list'>


In [6]:
# Create a program that writes a list of numbers to a pickle file. 
num = [1,2,3,4,5,6,7,8,9,10]
file = "mynum.pkl"
f = open(file,"wb")
pickle.dump(num,f)
f.close()

In [47]:
# Implement a program that generates a random number between a specified range. 

import random as rd

print(rd.randint(0,10))

6


In [61]:
# Write a program that simulates a dice roll. 

import random as rd

print(rd.randint(1,6))

7


In [65]:
# Create a function to calculate the factorial of a list of numbers. 

def fact(n):
    if n==1 & n==0:
        return 1
    else:
        return n*fact(n-1)
print(fact(5))

120


In [26]:
# Write a function that returns the greatest common divisor (GCD) of two numbers. 
def gcd(n1,n2):
    if n1 > n2:
        num = n2
    else:
        num = n1
    for i in range(1,num+1):
        if n1%i == 0 and n2%i == 0:
            prod = i
    return prod
num1 = int(input("Emter num1"))
num2 = int(input("Emter num2"))
print(gcd(num1,num2))


6


In [33]:
# Solve prime number using recursion. 

def fact(n,i=2):
    if i==n:
      return True  
    if n%i == 0:
        return False
    return fact(n,i+1)
num = int(input("Enter number"))
if fact(num):
   print("Entered number is prime")
else:
   print("Entered number is not prime")

Entered number is prime


In [5]:
# Write a program that counts the frequency of each character in a given string and stores it in a dictionary. 

d1 = {}
str = input("Enter a string")
str = str.replace(" ","")
print(str)
for ch in str:
    if ch in d1:
        d1[ch] += 1
    else:
        d1[ch] = 1
print(d1)

pinkal is good
{'p': 1, 'i': 2, 'n': 1, 'k': 1, 'a': 1, 'l': 1, ' ': 2, 's': 1, 'g': 1, 'o': 2, 'd': 1}


In [9]:
# Create a program that combines two dictionaries into a new one. 
dict1 = {"rabbit":[1,2,3,4],"tortoise":5678,"giraffe":"animal"}
dict2 = {"rab":[1,2],"to":"file","gi":78.90}
dict_new = dict1 | dict2
print(dict_new)

{'rabbit': [1, 2, 3, 4], 'tortoise': 5678, 'giraffe': 'animal', 'rab': [1, 2], 'to': 'file', 'gi': 78.9}


In [20]:
# Update, remove, add operations sort, threshold filtering. 
dict1 = {"rabbit":[1,2,3,4],"tortoise":5678,"giraffe":"animal"}
dict2 = {"rab":[1,2],"to":"file","gi":78.90}
dict3 = {"mango":1,"apple":5,"banana":7}

# Update 
dict1["rabbit"] = [4,5,6]

# Delete
del(dict1["tortoise"])
dict2.pop("to")
print(dict1,dict2)

# Add
dict2["open"] = "print"
print(dict2)

# Sorting
sorted_dict = sorted(dict3.keys())
print(dict3)
for key in sorted_dict:
    print(key,dict3[key])

sorted_items = sorted(dict3.items(), key=lambda x: x[0])
for key, value in sorted_items:
    print(key, value)

# Thresholding Filtering
dict4 = {'apple': 5, 'banana': 3, 'orange': 8} 
th = 4
filter_dict = {key : value for key,value in dict4.items() if value > th}
print(filter_dict)

{'rabbit': [4, 5, 6], 'giraffe': 'animal'} {'rab': [1, 2], 'gi': 78.9}
{'rab': [1, 2], 'gi': 78.9, 'open': 'print'}
{'mango': 1, 'apple': 5, 'banana': 7}
apple 5
banana 7
mango 1
apple 5
banana 7
mango 1
{'apple': 5, 'orange': 8}


In [23]:
# Implement a program that handles exceptions for division by zero. 
num = int(input("Enter a number"))
try:
    print(num/0)
except ZeroDivisionError:
    print("ZeroDivisionError: problem is occured")
finally:
    print("The error is solved")




ZeroDivisionError: problem is occured
The error is solved


In [8]:
# Write a program that prompts the user to enter a number and handles the Value Error if the input is not a valid number. 
try:
    num = input("Enter a number")
    num = int(num)
except ValueError:
    print("The input is not a valid number")
finally:
    print("The entered number is ",num)

   

The input is not a valid number
The entered number is  56y


#Array

In [2]:
from array import *

In [9]:
x = array('d',[])
arr1 = array('d',[1,2,3,4])
print(arr1)
for i in arr1:
    print("%d" % i,end= " ")

# a.append(x)
#a.count(x) 
#a.extend(x) 
#a.index(x) 
#a.insert(i,x) 
#a.pop() 
#a.pop(x) 
#a.remove(x) 
#a.reverse() 
#a.tofile(f) :- write elements in file f 
#a.tolist() :- convert elements in list  like a.tostring()
# a.fromfile(f,n):-reads from file and appends to end of array
# a.fromlist(f,n):-reads from list and appends to end of array
# a.fromstring(f,n):-reads from string and appends to end of array

array('d', [1.0, 2.0, 3.0, 4.0])
1 2 3 4 

In [10]:
import numpy as np

In [13]:
a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
a = np.logspace(1,4,5)
a

array([   10.        ,    56.23413252,   316.22776602,  1778.27941004,
       10000.        ])

In [35]:
a = np.arange(1,10+2); b=np.arange(10,1,-1)
a,b

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([10,  9,  8,  7,  6,  5,  4,  3,  2]))

In [40]:
a = np.zeros(5,int); b = np.ones(5)
a+b

array([1., 1., 1., 1., 1.])

sin,cos,tan,max,min,sum,mean,median,var,cov,std,argmin,argmax,unique,sort,concatenate functions can be done in numpy array

In [43]:
a = np.array([1,2,3,0])
b = np.array([0,2,3,1])

c= a == b
print("Result od a==b",c)
print("Result od a>b",a>b)
print("Result od a<=b",a<=b)
print("Check if any element is matching",any(c))
print("Check if all element is matching",all(c))


Result od a==b [False  True  True False]
Result od a>b [ True False False False]
Result od a<=b [False  True  True  True]
Check if any element is matching True
Check if all element is matching False


In [44]:
a = np.array([1,2,3],int)
b = np.array([0,2,3],int)
c = np.logical_and(a>0,a<4)
print(c)
c = np.logical_or(b>=0,b==1)
print(c)
c = np.logical_not(a>0,a<4)
print(c)

[ True  True  True]
[ True  True  True]
[False False False]


a = b Just aliasing
b = a.view() is modify can modify the original
b = a.copy() is having seperate 2 arrays independent of each other

In [58]:
a =  np.array([[1,2,34,4],[1,2,3,4]],int)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.dtype)
print(a.nbytes)
print(a.reshape(4,2))
print(a.flatten())

2
(2, 4)
8
4
int32
32
[[ 1  2]
 [34  4]
 [ 1  2]
 [ 3  4]]
[ 1  2 34  4  1  2  3  4]


A python program to accept two matrices and find it's product

In [63]:
import numpy as np
import sys

r1, c1 = [int(a) for a in input("First matric rows , columns : ").split()]
r2, c2 = [int(a) for a in input("Second matric rows , columns : ").split()]
if c1!=r2:
    print("Multiplication is not possible")
    sys.exit()
str1 = input("First matrix elements")
x = np.reshape(np.matrix(str1),(r1,c1))
print(x)
str2 = input("Second matrix elements")
y = np.reshape(np.matrix(str2),(r2,c2))
print(y)
z = x*y
print(z)

[[1 2 3]
 [4 5 6]]
[[ 1  0]
 [ 0  2]
 [ 1 -1]]
[[ 4  1]
 [10  4]]


Generators

In [17]:
# Fibonacci Generator: 

# Implement a generator that generates the Fibonacci sequence up to a specified limit.

def fib_generator(n):
    a  = 0;b=1
    while(a < n):
       
        yield a 
        a,b =b,a+b

num = int(input())
for i in fib_generator(num):
    print(i)

0
1
1
2
3


Decorators

In [1]:
def decor(fun):
    def inner():
        value = fun()
        return value+2
    return inner

def num():
    return 10

result_fun = decor(num)
print(result_fun())



12


In [24]:
# Timing Decorator: Implement a decorator that calculates and prints the execution time of a function. 
import time

def decor(func):
    def run_time():
        val = func()
        print("The running time is ",val-time.time()+1)
    return run_time

@decor
def str_time():
    print("The start time is ",time.time())
    return time.time() 

str_time()




The start time is  1706186952.6722326
The running time is  1.0


In [19]:
# Memorization Decorator: 

# Create a decorator for memorization, which stores the results of expensive function calls and returns the cached result when the same inputs occur again. 

def decor(func):
    cache = {}

    def memorize(*args):
        # val = func()
        # lst = []
        if args not in cache:
            # lst.append(val)
            # print(lst)
            cache[args] = func(args)
            # val_inp()
            return cache[args]
        # result = func(*args)
        # cache[args] = result
        # return result
        # else:
            # print(lst)
    return memorize

@ decor
def val_inp():
    val  = input("Enter Your name")
    val_inp(val)
    return val

val_inp()
        


TypeError: val_inp() takes 0 positional arguments but 1 was given

In [13]:
# Authentication Decorator: 

# Implement a decorator that checks if a user is authenticated before allowing access to a specific function. 
def decor(func):
    cn = {"pinkal":"1234"}
    def authenticate(*args,**kwargs):
        val = func(*args,**kwargs)
        val = args[0]
        if args[0] in cn and cn[args[0]] == args[1]:
            print("Authenticate")
        else:
            print("Invalid username and password")
    return authenticate

@decor
def user(id1,pass1):
   return 0


user_id = input("Enter name")
user_pass = input("Enter a passsword")
user(user_id,user_pass)

Authenticate


Context Managers

Context managers allow you to allocate and release resources precisely when you want to. The most widely used example of context managers is the with statement.

A common use case of context managers is locking and unlocking resources and closing opened files

The context manager object results from evaluating the expression after with. In other words, expression must return an object that implements the context management protocol. This protocol consists of two special methods:

.__enter__() is called by the with statement to enter the runtime context.
.__exit__() is called when the execution leaves the with code block.

Creating Sample Context Managers

In [1]:
class HelloContextManager:
    def __enter__(self):
        print("Entering the context...")
        return "Hello, World!"
    def __exit__(self,exc_type, exc_value, exc_tb ):
        print("Leaving the context...")
        print(exc_type, exc_value, exc_tb , sep="\n")

with HelloContextManager() as hello:
    print(hello)

Entering the context...
Hello, World!
Leaving the context...
None
None
None


In [11]:
with HelloContextManager() as hello:
    print(hello)
    hello[12]
    hello[100]

Entering the context...
Hello, World!
Leaving the context...
<class 'IndexError'>
string index out of range


IndexError: string index out of range

exc_type is the exception class, IndexError.
exc_value is the exception instance.
exc_tb is the traceback object.

Handling Exceptions in a Context Manager

In [12]:
class HelloContextManager:
    def __enter__(self):
        print("Entering the context...")
        return "Hello, World!"
    def __exit__(self,exc_type, exc_value, exc_tb ):
        print("Leaving the context...")
        if isinstance(exc_value, IndexError):
            print(f"An exception occured in your with block: {exc_type}")
            print(f"Exception message: {exc_value}")
            return True
        

with HelloContextManager() as hello:
    print(hello)
    hello[100]

print("Continue normally from here...")

Entering the context...
Hello, World!
Leaving the context...
An exception occured in your with block: <class 'IndexError'>
Exception message: string index out of range


Timer Context Manager: 

Develop a context manager that measures and prints the time taken for the code block inside it to execute. 

In [14]:
from time import perf_counter

class Timer:
    def __enter__(self):
        self.start = perf_counter()
        self.end = 0.0
        return lambda: self.end - self.start
    
    def __exit__(self,*args):
        self.end = perf_counter()

In [15]:
from time import sleep 

with Timer() as timer:
    sleep(0.5)

timer()

0.5002613998949528

File Handling Context Manager: 

Create a context manager for file handling that ensures proper opening and closing of a file. 

In [16]:
class FileHandling:
    def __init__(self,file_name,mode):
        self.file = open(file_name,mode)
    def __enter__(self):
        return self.file
    def __exit__(self,type,value,traceback):
        self.file.close()


In [21]:
with FileHandling("file.txt",'') as f:
    f.write('hello you have made context manager\n')

### Object-Oriented Programming: 

#### Bank Account Class: 

Design a Bank Account class that includes methods for deposit, withdrawal, and checking the balance. 

In [1]:
class Bank():
    bal = 100
    def __init__(self,name):
        self.name = name
        print("Hello ",name," Welcome")

    def deposit (self):
        w = int(input("Amount you want to deposit"))
        self.bal = self.bal + w
        self.check_balance()

    def withdraw(self):
        w =  int(input("Amount you want to withdraw"))
        if self.bal < w:
            print("Insufficient Balance")
        else:
            self.bal =  self.bal - w
        self.check_balance()
            
    def check_balance(self):
        print(f"Your current balance is {self.bal}")
        


In [2]:
print("Welcome to bank")
print("For Deposit Enter 1 \n For withdraw Enter 2 \n For Balance Check Enter 3 \n For Quit press 4")
inp = int(input("Enter number"))
name = input("Please enter your name :")
bnk = Bank(name)

while(inp != 4):
    if(inp == 1):
        bnk.deposit()
    elif(inp == 2):
        bnk.withdraw()
    elif(inp == 3):
        bnk.check_balance()
    else:
        print("Wrong input!  \n Please try again")
# switch = {1 : Bank.deposit(),2 : Bank.withdraw(),3 : Bank.check_balance(),4 : Bank.exit()}
# with open("bank_acc.txt","w+") as f:
    # f.write()

Welcome to bank
For Deposit Enter 1 
 For withdraw Enter 2 
 For Balance Check Enter 3 
 For Quit press 4


ValueError: invalid literal for int() with base 10: ''

#### Inheritance: (Is-A Relation)



##### The super() Function
The super() function is a built-in function that returns the objects that represent the parent class. It allows to access the parent class’s methods and attributes in the child class.

Different types of Python Inheritance
There are 5 different types of inheritance in Python. They are as follows:

<b>Single inheritance</b>: When a child class inherits from only one parent class, it is called single inheritance. We saw an example above.
<br>
<b>Multiple inheritances</b>: When a child class inherits from multiple parent classes, it is called multiple inheritances. 
<br>
<b>Multilevel inheritance</b>: When we have a child and grandchild relationship. This means that a child class will inherit from its parent class, which in turn is inheriting from its parent class.
<br>
<b>Hierarchical inheritance</b> More than one derived class can be created from a single base.
<br>
<b>Hybrid inheritance</b>: This form combines more than one form of inheritance. Basically, it is a blend of more than one type of inheritance.

Create a base class Shape and derived classes Circle and Rectangle. Include methods to calculate the area and perimeter for each shape. 

In [20]:
import math

class Shape:
    def __init__(self):
        # rad = int(input("Enter radius"))
        # length = float(input("Enter a length"))
        # print(rad,length)
        pass

class Circle(Shape):
    def __init__(self):
        super().__init__()
        self.r = float(input("Enter radius"))
    
    def area(self):
        area = math.pi *(pow(self.r,2))
        print(area)

    def perimeter(self):
        peri = 2 * math.pi * self.r
        print(peri)

class Rectangle(Shape):
    
    def __init__(self):
        super().__init__()
        self.length = float(input("Enter a length"))
        self.breadth = float(input("Enter a length"))

    def area(self):
        area = self.length*self.breadth
        print(area)

    def perimeter(self):
        peri = 2*(self.length+self.breadth)
        print(peri)

In [24]:
Shape()
Circle().area()
Rectangle().perimeter()

28.274333882308138
18.0


### Composition: (Has-A Relation)

Design a class representing a Library that contains books. Each book can have multiple authors. Use composition to represent the relationship between the library and books. 

In [79]:
class Library:
    dict1 = {
    "To Kill a Mockingbird": "Harper Lee",
    "1984": ["George Orwell","Pinkal"],
    "Pride and Prejudice": "Jane Austen",
    "The Great Gatsby": "F. Scott Fitzgerald",
    "Moby-Dick": "Herman Melville",
    "War and Peace": "Leo Tolstoy",
    "The Catcher in the Rye": "J.D. Salinger",
    "The Lord of the Rings": "J.R.R. Tolkien",
    "The Chronicles of Narnia": "C.S. Lewis",
    "Frankenstein": "Mary Shelley"
    }
    def __init__(self):
        # print(self.dict1)
        # print("Youa are in init of Library")
        pass

    def show_books(self):
        # print("Youa are in show_books of Library")
        for k in self.dict1:
            print(k)

class Book:
    def __init__(self,book):
        # print("Youa are in init of Book")
        
        self.book = book
        # print(self.book)
        
    
    def show_author(self):
        # print("Youa are in show_author of Book")
        obj = Library()
        dict1 = obj.dict1
        # print(obj.dict1)
        if self.book in dict1:
            print(dict1[self.book])
        else:
            print("Book is not available")



In [63]:
Library()

{'To Kill a Mockingbird': 'Harper Lee', '1984': ['George Orwell', 'Pinkal'], 'Pride and Prejudice': 'Jane Austen', 'The Great Gatsby': 'F. Scott Fitzgerald', 'Moby-Dick': 'Herman Melville', 'War and Peace': 'Leo Tolstoy', 'The Catcher in the Rye': 'J.D. Salinger', 'The Lord of the Rings': 'J.R.R. Tolkien', 'The Chronicles of Narnia': 'C.S. Lewis', 'Frankenstein': 'Mary Shelley'}
Youa are in init of Library


In [64]:
Library().show_books()

{'To Kill a Mockingbird': 'Harper Lee', '1984': ['George Orwell', 'Pinkal'], 'Pride and Prejudice': 'Jane Austen', 'The Great Gatsby': 'F. Scott Fitzgerald', 'Moby-Dick': 'Herman Melville', 'War and Peace': 'Leo Tolstoy', 'The Catcher in the Rye': 'J.D. Salinger', 'The Lord of the Rings': 'J.R.R. Tolkien', 'The Chronicles of Narnia': 'C.S. Lewis', 'Frankenstein': 'Mary Shelley'}
Youa are in init of Library
Youa are in show_books of Library
To Kill a Mockingbird
1984
Pride and Prejudice
The Great Gatsby
Moby-Dick
War and Peace
The Catcher in the Rye
The Lord of the Rings
The Chronicles of Narnia
Frankenstein


In [81]:
Book("1984").show_author()

['George Orwell', 'Pinkal']


### Polymorphism: 

Implement a class hierarchy for different types of animals. Use polymorphism to create a function that prints the sound each animal makes. 

In [88]:
class Animal:
    def speak(self):
        True

class Dog(Animal):
    def speak(self):
        print("Woof")
        
class Cat(Animal):
    def speak(self):
        print("M,eow!!")

In [89]:
animal = [Dog(),Cat()]
for a in animal:
    print(a.speak())

Woof
None
M,eow!!
None
